// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const isTestEnv = import.meta.env.MODE === 'test' || Boolean(import.meta.env.VITEST);
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || (isTestEnv ? 'http://127.0.0.1:54321' : undefined);
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || (isTestEnv ? 'test-publishable-key' : undefined);

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Supabase environment variables are required.');
}

const storage = typeof localStorage !== 'undefined'
  ? localStorage
  : undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    // Use PKCE flow for better security and mobile compatibility
    flowType: 'pkce',
  }
});
